config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #Path to root page
  root to: 'public#index', as: 'root'
  get '/about', to: 'public#about', as: 'about'
  get '/api', to: 'public#api', as: 'api'

  #User handling routes
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations, :unlocks]

  match 'lang/:locale', to: 'visitors#change_locale', as: :change_locale, via: [:get]

  #Update user profile
  #get '/user/edit', to: 'users/users#edit', as: 'user_edit'
  put '/user/edit', to: 'users#update', as: 'user_update'

  ###############################################################
  devise_scope :user do

    get '/signin', to: 'users/sessions#new', as: 'new_user_session'
    post '/signin', to: 'users/sessions#create', as: 'user_session'
    get '/signout', to: 'users/sessions#sdestroy', as: 'secure_destroy_user_session'
    delete '/signout', to: 'users/sessions#destroy', as: 'destroy_user_session'

    # registrations
    get '/signup', to: 'users/registrations#new', as: 'new_user_registration'
    post '/signup', to: 'users/registrations#create', as: 'user_registration'

    # user accounts
    scope '/account' do
      # confirmation
      get '/verification', to: 'users/confirmations#verification_sent', as: 'user_verification_sent'
      get '/confirm', to: 'users/confirmations#show', as: 'user_confirmation'
      get '/confirm/resend', to: 'users/confirmations#new', as: 'new_user_confirmation'
      post '/confirm', to: 'users/confirmations#create'

      # passwords
      get '/reset-password', to: 'users/passwords#new', as: 'new_user_password'
      get '/reset-password/change', to: 'users/passwords#edit', as: 'edit_user_password'
      put  '/reset-password', to: 'users/passwords#update', as: 'user_password'
      post '/reset-password', to: 'users/passwords#create'

      # unlocks
      post '/unlock', to: 'users/unlocks#create', as: 'user_unlock'
      get '/unlock/new', to: 'users/unlocks#new', as: 'new_user_unlock'
      get '/unlock', to: 'users/unlocks#show'

      # settings & cancellation
      get '/cancel', to: 'users/registrations#cancel', as: 'cancel_user_registration'
      get '/settings', to: 'users/registrations#edit', as: 'edit_user_registration'
      put '/settings', to: 'users/registrations#update', as: 'update_user_registration'
      # account deletion
      delete '/delete', to: 'users/registrations#destroy', as: 'destroy_user_registration'
    end
  end
  #User account paths
  get '/account', to: 'users#account', as: 'account'
  get '/account/edit_news', to: 'users/contents#edit_news'
  put '/account/update_news', to: 'users/contents#update_news'
  #Upgrade profile
  get '/upgrade', to: 'users#upgrade', as: 'upgrade_profile'
  ################################################################


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',
                                  controllers: {
                                      sessions: 'api/v1/devise_token_auth/sessions',
                                      registrations: 'api/v1/devise_token_auth/registrations',
                                  }

      post '/auth_check_confirmable', to: 'users#auth_check_confirmable', as: 'auth_check_confirmable'

      resources :devices, only: [ :create ]
      resources :toll_devices, only: [ :index ]
      resources :locations, only: [ :create ]
      resources :vehicles, only: [ :index, :show, :create, :update, :destroy ]
      resources :docks, only: [ :index, :show, :create, :update, :destroy ]

      post '/analyze', to: 'alpr#analyze', as: 'alpr_analyze'
      post '/get_vehicle_history', to: 'toll_devices#get_vehicle_history', as: 'get_vehicle_history'
      post '/check_declined', to: 'toll_devices#check_declined', as: 'check_declined'
      post '/submit_payment', to: 'parking_payments#submit', as: 'submit_payment'
    end
  end

  #vehicles index path
  get '/vehicles', to: 'users/vehicles#index', as: 'vehicles'
  #ships index path
  get '/ships', to: 'users/ships#index', as: 'ships'
  #ships list path
  get '/ship/list', to: 'users/ships#list', as: 'ship_list'
  #docks index path
  get '/docks', to: 'users/docks#index', as: 'docks'
  #docks list path
  get '/dock/list', to: 'users/docks#list', as: 'dock_list'
  #shedules index path
  get '/schedules', to: 'users/schedules#index', as: 'schedules'
  #drivers index path
  get '/drivers', to: 'users/drivers#index', as: 'drivers'
  #services index path
  get '/services', to: 'users/services#index', as: 'services'
  # business index path
  get '/businesses', to: 'users/businesses/business#index', as: 'business'
  # payments index path
  get '/payments' => 'users/payments#index', as: 'payment'
  # address index path
  get '/address', to: 'users/businesses/address#index', as: 'address'
  # contacts index path
  get '/contacts', to: 'users/businesses/contacts#index', as: 'contacts'
  # contacts index path
  get '/business_payments', to: 'users/businesses/business_payments#index', as: 'business_payments'
  # contacts index path
  get '/parking_payments', to: 'users/parking_payments#index', as: 'parking_payments'
  # contacts index path
  get '/road_payments', to: 'users/road_payments#index', as: 'road_payments'


  scope :users do

    # Vehicle new routes
    get '/vehicle/new', to: 'users/vehicles#new', as: 'vehicle_new'
    post '/vehicle/new', to: 'users/vehicles#create', as: 'vehicle_create'

    resources :vehicles, only:[] do
      get '/edit', to: 'users/vehicles#edit', as: 'edit'
      put '/edit', to: 'users/vehicles#update', as: 'update'
      delete '/delete', to: 'users/vehicles#destroy', as: 'destroy'
    end

    #Drivers routes
    get '/driver/new', to: 'users/drivers#new', as: 'driver_new'
    post '/driver/new', to: 'users/drivers#create', as: 'driver_create'
    get '/show', to: 'users/drivers#show', as: 'driver_show'
    resources :drivers, only:[] do
      get '/edit', to: 'users/drivers#edit', as: 'edit'
      put '/edit', to: 'users/drivers#update', as: 'update'
      delete '/delete', to: 'users/drivers#destroy', as: 'destroy'
    end

    #Services routes
    get '/service/new', to: 'users/services#new', as: 'service_new'
    post '/service/new', to: 'users/services#create', as: 'service_create'
    get '/show', to: 'users/services#show', as: 'service_show'
    resources :services, only:[] do
      get '/edit', to: 'users/services#edit', as: 'edit'
      put '/edit', to: 'users/services#update', as: 'update'
      delete '/delete', to: 'users/services#destroy', as: 'destroy'
    end

    # parking payments routes
    get '/parking_payment/new', to: 'users/parking_payments#new', as: 'parking_payment_new'
    post '/parking_payment/new', to: 'users/parking_payments#create', as: 'parking_payment_create'

    resources :parking_payments, only:[] do
      get '/show', to: 'users/parking_payments#show', as: 'show'
      get '/edit', to: 'users/parking_payments#edit', as: 'edit'
      put '/edit', to: 'users/parking_payments#update', as: 'update'
      delete '/delete', to: 'users/drivers#destroy', as: 'destroy'
    end

    post '/parking_payments/submit', to: 'users/parking_payments#submit', as: 'payment_submit'

    scope :businesses do
      # business path
      get '/business/new', to: 'users/businesses/business#new', as: 'business_new'
      post '/business/new', to: 'users/businesses/business#create', as: 'business_create'

      resources :business, only:[] do
        #User business update and destroy paths
        get '/show', to: 'users/businesses/business#show', as: 'show'
        get '/edit', to: 'users/businesses/business#edit', as: 'edit'
        put '/edit', to: 'users/businesses/business#update', as: 'update'
        delete '/delete', to: 'users/businesses/business#destroy', as: 'destroy'
      end

      # toll_devices path
      get '/toll_device/new', to: 'users/businesses/toll_devices#new', as: 'toll_device_new'
      post '/toll_device/new', to: 'users/businesses/toll_devices#create', as: 'toll_device_create'

      resources :toll_devices, only:[] do
        #User business update and destroy paths
        get '/show', to: 'users/businesses/toll_devices#show', as: 'show'
        get '/edit', to: 'users/businesses/toll_devices#edit', as: 'edit'
        put '/edit', to: 'users/businesses/toll_devices#update', as: 'update'
        delete '/delete', to: 'users/businesses/toll_devices#destroy', as: 'destroy'
      end

      # Address new,create routes
      get '/address/new', to: 'users/businesses/address#new', as: 'address_new'
      post '/address/new', to: 'users/businesses/address#create', as: 'address_create'

      resources :address, only:[] do
        # Address show, edit, update, delete routes
        get '/show', to: 'users/businesses/address#show', as: 'show'
        get '/edit', to: 'users/businesses/address#edit', as: 'edit'
        put '/edit', to: 'users/businesses/address#update', as: 'update'
        delete '/delete', to: 'users/businesses/address#destroy', as: 'destroy'
      end

      # Contacts new,create routes
      get '/contact/new', to: 'users/businesses/contacts#new', as: 'contact_new'
      post '/contact/new', to: 'users/businesses/contacts#create', as: 'contact_create'

      resources :contacts, only:[] do
        # Address show, edit, update, delete routes
        get '/show', to: 'users/businesses/contacts#show', as: 'show'
        get '/edit', to: 'users/businesses/contacts#edit', as: 'edit'
        put '/edit', to: 'users/businesses/contacts#update', as: 'update'
        delete '/delete', to: 'users/businesses/contacts#destroy', as: 'destroy'
      end

      # Payment new,create routes
      get '/business_payment/new', to: 'users/businesses/business_payments#new', as: 'business_payment_new'
      post '/business_payment/new', to: 'users/businesses/business_payments#create', as: 'business_payment_create'

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :name, presence: true

  #image url method
  def image_url

    #fetch video image url
    @image_url = self.service_image_url

      #if company image is blank or missing
      if @image_url.nil? or @image_url.blank?

        @image_url = "https://vgy.me/zJB9id.png" #Set no image supplied

      else

        @image_url #return company image

      end
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  before_action :authenticate_user!, except: [:auth_check_confirmable]

  # App Auto Devise Confirmable support
  def auth_check_confirmable
    @user_login = params[:login]
    @user = User.where(["lower(username) = :login OR lower(email) = :login", { :login => @user_login.downcase }]).first
    if @user
      render json: {
          status: 200,
          message: "Response successfully sent!",
          confirmed: @user.confirmed?
      }.to_json
    else
      render json: {
          status: 400,
          message: "Response successfully sent with ERRORS!",
          errors: "User doesn't exist!"
      }.to_json
    end
  end

  # Upgrading user profile and giving driver/business roles
  def upgrade(param)

    if param == "driver"
      @driver = Driver.new(driver_params)
      @driver.user_id = @current_user.id
      respond_to do |format|
        if @driver.save
          format.html { redirect_to account_path, notice: 'driver was successfully created.' }
          format.json { render :show, status: :created, location: @driver }
          @current_user.driver!
        else
          redirect_back_or_default(root_path, :alert => "Something went wrong!.")
        end
      end
    elsif param == "business"
      @business = Business.new(business_params)
      @business.user_id = @current_user.id
      respond_to do |format|
        if @business.save
          format.html { redirect_to business_path, notice: 'business was successfully created.' }
          format.json { render :show, status: :created, location: @business }
          @current_user.business!
        else
          format.html { render :new }
          format.json { render json: @business.errors, status: :unprocessable_entity }
        end
      end
    else
        flash[:notice] = "Bad role!"
    end
  end


  # Only allow a trusted parameter "white list" through.
  def driver_params
    if Rails::VERSION::MAJOR < 4
      params[:driver].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:driver).permit(Driver.new.attributes.keys - protected_attrs, :_destroy)
    end
  end


  # Only allow a trusted parameter "white list" through.
  def business_params
    if Rails::VERSION::MAJOR < 4
      params[:business].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:business).permit(Business.new.attributes.keys - protected_attrs, :_destroy)
    end
  end
end

app/controllers/users/businesses/address_controller.rb
class Users::Businesses::AddressController < ApplicationController
  before_action :authenticate_user!
  before_action :set_business, only: [:create, :new]


  def index
    @addresses = Address.where(:business_id => @current_user.business.ids)
  end

  def new
    @address = Address.new
  end

  def show

  end

  def create
    @address = Address.new(address_params)
    @address.business_id = @current_user.business.first.id
    respond_to do |format|
      if @address.save
        format.html { redirect_to account_path, notice: 'Address was successfully created.', locals: { myclass: 'alert alert-success' } }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    if @business.update(address_params)
      redirect_to account_path
      #redirect_to request_user_show_path(@request)
    else
      redirect_back_or_default(root_path, :alert => "Something went wrong!.")
    end
  end

  private

  def set_address
    @address = Address.find(params[:address_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_business
    @business = Business.find_by(:user_id => @current_user.id)
    if @business.present?
      @business
    else
      redirect_back_or_default(root_path, :alert => "You have to create business first!")
    end
  end

  def address_params
    if Rails::VERSION::MAJOR < 4
      params[:address].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:address).permit(Address.new.attributes.keys - protected_attrs, :_destroy)
    end
  end
end

app/controllers/users/businesses/business_controller.rb
class Users::Businesses::BusinessController < ApplicationController
  before_action :set_business, only: [:show, :update, :destroy]
  before_action :business_only, only: [:new, :create]
  before_action :authenticate_user!

  # GET /business
  def index
    @businesses = Business.where(:user_id => @current_user.id)
  end

  def new
    @business = Business.new
  end


  # GET /businesss/1
  def show

    #render json: @business
  end

  #Edit /businesss/:id/
  def edit

  end

  # POST /businesss
  def create
    @business = Business.new(business_params)
    @business.user_id = @current_user.id
    respond_to do |format|
      if @business.save
        format.html { redirect_to account_path, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
        @current_user.business!
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesss/1
  def update
    if @business.update(business_params)
      redirect_to account_path
      #redirect_to request_user_show_path(@request)
    else
      redirect_back_or_default(root_path, :alert => "Something went wrong!.")
    end
  end

  # DELETE /businesss/1
  def destroy

    @business.destroy
    redirect_to business_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_business
    @business = Business.find(params[:business_id])
  end

  def business_only

    @business = Business.find_by(:user_id => @current_user.id)
    if @business
      redirect_back_or_default(root_path, :alert => t("messages.business.permission_failed"))
    end

  end


  # Only allow a trusted parameter "white list" through.
  def business_params
    if Rails::VERSION::MAJOR < 4
      params[:business].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:business).permit(Business.new.attributes.keys - protected_attrs, :_destroy)
    end
  end
end

app/controllers/users/businesses/business_payments_controller.rb
class Users::Businesses::BusinessPaymentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @business_payments = BusinessPayment.all
  end

  def user_payments
    @business_payments = BusinessPayment.where(:users_id => @current_user.id)
  end

  def create

  end

  def show

  end

  def edit

  end

  def update

  end

  private


  def set_payment
    @business_payment = BusinessPayment.find(params[:business_payment_id])
  end


  def payment_params
    if Rails::VERSION::MAJOR < 4
      params[:business_payment].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:business_payment).permit(Contact.new.attributes.keys - protected_attrs, :_destroy)
    end
  end
end

app/views/users/services/_form.html.erb
<div class="col-md-8 col-md-offset-2 request-fields">
    <div class="col-md-12 form-group">
      <%= f.label t("users.services.service_fields.name") %>
      <%= f.text_field :name, :class => 'form-control', :"data-fv-notempty"=>"true", :"data-fv-notempty-message"=>"Please enter your service license number."  %>
      <%= f.label t("users.services.service_fields.description") %>
      <%= f.input :description, label: false%>
      <%= f.label t("users.services.service_fields.price") %>
      <%= f.input :price, label: false%>
    </div>
    <div class="col-md-12 form-group">
      <div class="fileinput-image">
        <% unless @service.service_image_url.nil? %>
          <img src="<%= @service.service_image_url %>" style="width:250px; height:250px" >
        <% else %>
          <h5><%= t("users.vehicles.vehicle_fields.no-image") %></h5>
        <% end %>
      </div>

      <span class="btn btn-success fileinput-button">
        <div class="col-2" style="margin-left: 50px">
            <%= f.file_field :service_image_url, accept: '*', data: { 'resource-name' => 'image'}, :class => "vgyme_image_upload" %>
        </div>
        <!-- Change based on action -->
        <% if current_page?(action: 'new') || @service.service_image_url.nil? %>
          <span><%= t("users.vehicles.vehicle_fields.upload-image") %></span>
        <% else %>
          <span><%= t("users.vehicles.vehicle_fields.change-image") %></span>
        <% end %>
      </span>
    </div>
</div>




<script>
  $(document).ready(function(){
      InitFileUpload();
  });
</script>

app/views/users/services/edit.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">
      <h1 class="text-center form-title"><%= t("users.services.edit.title") %></h1>
      <%= simple_form_for(@service, :url => service_update_path(@service),:method => 'put',  :html => { :id => "form_service", :class => 'form-group directFileUpload custom-form', :role => 'form'}) do |f| %>
        <%= render 'form', f: f %>
        <div class="col-md-8 col-md-offset-2 d-flex justify-content-center">
          <%= f.button :submit, t("users.services.edit.save-button"), :class => 'btn btn-primary' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<script>
    $(document).ready(function(){
        InitFileUpload();
    });
</script>

app/views/users/services/index.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">
      <section id="page-title">

        <div class="container clearfix">
          <h1><%= t("users.services.index.title") %></h1>
        </div>

      </section><!-- #page-title end -->
      <section id="content">
        <div class="content-wrap">

          <div class="container clearfix">
            <% @services.each do |service|%>
              <div class="col_one_third nobottommargin" style="margin-left: -15px;">
                <div class="feature-box media-box">
                  <div class="fbox-media">
                    <img src="<%= service.service_image_url %>" alt="Why choose Us?">
                  </div>
                  <div class="fbox-desc">
                    <h3><%= service.name %><span class="subtitle"><%= service.expiry_date %></span></h3>
                    <p><%= service.description %></p>
                  </div>
                  <a href="<%= service_show_path(service) %>">Learn more &rarr;</a>
                  <a href="<%= service_edit_path(service) %>" style="float: right">Edit</a>
                </div>
              </div>
            <% end %>
          </div>

        </div>
      </section><!-- #content end -->
      <div class="d-flex justify-content-center" style="margin-bottom: 40px;">
        <%= link_to t("users.services.index.create-button"), service_new_path, :class => 'btn btn-primary '%>
      </div>
    </div>
  </div>
</div>

<script>

    var randomScalingFactor = function() {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'doughnut',
        data: {
            datasets: [{
                data: [
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                ],
                backgroundColor: [
                    window.chartColors.red,
                    window.chartColors.orange,
                    window.chartColors.yellow,
                    window.chartColors.green,
                    window.chartColors.blue,
                ],
                label: 'Dataset 1'
            }],
            labels: [
                "Red",
                "Orange",
                "Yellow",
                "Green",
                "Blue"
            ]
        },
        options: {
            responsive: true,
            legend: {
                display: false,
                position: 'top',
            },
            title: {
                display: false,
                text: 'Doughnut Chart'
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        }
    };


    // Radar Chart

    var color = Chart.helpers.color;
    var configRadar = {
        type: 'radar',
        data: {
            labels: [["Eating", "Dinner"], ["Drinking", "Water"], "Sleeping", ["Designing", "Graphics"], "Coding", "Cycling", "Running"],
            datasets: [{
                label: "My First dataset",
                backgroundColor: color(window.chartColors.red).alpha(0.2).rgbString(),
                borderColor: window.chartColors.red,
                pointBackgroundColor: window.chartColors.red,
                data: [
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor()
                ]
            }, {
                label: "My Second dataset",
                backgroundColor: color(window.chartColors.blue).alpha(0.2).rgbString(),
                borderColor: window.chartColors.blue,
                pointBackgroundColor: window.chartColors.blue,
                data: [
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor()
                ]
            },]
        },
        options: {
            legend: {
                display: false
            },
            title: {
                display: false
            },
            scale: {
                ticks: {
                    beginAtZero: true
                }
            }
        }
    };

    window.onload = function() {
        var ctx = document.getElementById("chart-doughnut").getContext("2d");
        window.myDoughnut = new Chart(ctx, config);
        window.myRadar = new Chart(document.getElementById("chart-radar"), configRadar);
    };

</script>

app/views/users/services/new.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">

        <h1 class="text-center"><%= t("users.services.new.title") %> </h1>

        <%= simple_form_for(@service, :url => service_new_path(@service), :html => { :id => "form_service", :class => 'form-group directFileUpload custom-form', :role => 'form'}) do |f| %>
          <%= render 'form', f: f %>

          <div class="col-md-8 col-md-offset-2 d-flex justify-content-center">
            <%= f.button :submit, t("users.services.new.create-button"), :class => 'btn btn-primary' %>
          </div>
        <% end %>

    </div>
  </div>
</div>

app/views/users/services/show.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">
      <h1 class="text-center form-title"><%= @service.name%></h1>


    </div>
  </div>
</div>